language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20.0
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build/
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile
script:
  - mix credo
  - mix test
